just for getting feedback from mentor. I'm not sure that i'm moving i…
163onmyneck/online-shop-spring pull request #11
Opened 2024-04-23 16:04 UTC by 163onmyneck

…n a right way.

2024-04-24 06:43 UTC, MAMentorFX requested changes

2024-04-24 06:43 UTC, MAMentorFX commented on src/main/java/com/example/demo/controller/ShoppingCartController.java
> +        return shoppingCartService.getByUserId(currentUser);
You can make only one call to DB having user Email. Just use SQL JOIN to have.

2024-04-24 06:43 UTC, MAMentorFX commented on src/main/java/com/example/demo/controller/ShoppingCartController.java
> +            getShoppingCart(authentication));
In Spring Boot, it's generally not recommended for controller methods to directly call each other. Controller methods are typically designed to handle incoming HTTP requests and delegate processing to services or other components. Directly calling one controller method from another can lead to tight coupling between them, making the code harder to understand, test, and maintain.

Instead, it's better to extract common functionality into separate service classes and have the controller methods delegate to these services. This promotes separation of concerns and allows for better code organization and reusability. Additionally, services can be easily tested in isolation, which is crucial for maintaining code quality.

2024-04-24 06:43 UTC, MAMentorFX commented on src/main/java/com/example/demo/controller/ShoppingCartController.java
> +        cartItemService.getById(id).setQuantity(quantity);
Controllers should not do any business logic, the just call proper services. setQuantity is the business logic.

2024-04-24 06:43 UTC, MAMentorFX commented on src/main/java/com/example/demo/service/cart/item/impl/CartItemServiceImpl.java
> +    public void deleteById(Long id) {
put the @Transactional on this method. You don't save the entity

2024-04-24 06:43 UTC, MAMentorFX commented on src/main/java/com/example/demo/service/cart/item/impl/CartItemServiceImpl.java
> +    }
put the @Transactional on this method. You don't save the entity

2024-04-24 06:43 UTC, MAMentorFX commented on src/main/java/com/example/demo/service/cart/item/impl/CartItemServiceImpl.java
> +    public CartItemResponseDto saveItemToShoppingCart(CartItemRequestDto cartItemRequestDto,
@Transactional. You make more than one call to DB

2024-04-24 06:43 UTC, MAMentorFX commented on src/main/java/com/example/demo/service/shopping/cart/ShoppingCartService.java
> +
```suggestion
```

2024-04-24 06:43 UTC, MAMentorFX commented on src/main/java/com/example/demo/repository/shopping/cart/ShoppingCartRepository.java
> +    ShoppingCart findByUserId(@Param("id") Long id);
It should return Optional

2024-04-25 10:50 UTC, Rommelua requested changes

2024-04-25 10:50 UTC, Rommelua commented on src/main/java/com/example/demo/mapper/BookMapper.java
> +    default Book bookFromId(Long id, @Context BookRepository bookRepository) {
mapper layer can not use repository

2024-04-25 10:50 UTC, Rommelua commented on src/main/java/com/example/demo/mapper/CartItemMapper.java
> +    CartItem toModel(CartItemRequestDto cartItemRequestDto, @Context BookRepository bookRepository);
mapper layer can not use repository

2024-04-25 10:50 UTC, Rommelua commented on src/main/java/com/example/demo/model/ShoppingCart.java
> +    @ManyToOne
one to one

2024-04-25 12:25 UTC, kerrrusha approved these changes

2024-04-25 13:37 UTC, merged