added tests for BookController, CategoryController, BookServiceImpl, …
163onmyneck/online-shop-spring pull request #14
Opened 2024-07-17 11:43 UTC by 163onmyneck

<img width="612" alt="1" src="https://github.com/user-attachments/assets/995c665d-7552-49a9-972e-194748cd349c">
<img width="596" alt="image" src="https://github.com/user-attachments/assets/92a3d5e9-4b78-4e66-a2f5-07e4874a8664">
<img width="613" alt="image" src="https://github.com/user-attachments/assets/0076cdfe-3ae6-4ff5-baa7-9a1fc2363de6">
<img width="619" alt="image" src="https://github.com/user-attachments/assets/862e00ef-cac9-41cf-87b1-e613d2c24acc">

2024-07-18 11:25 UTC, MentorMateAcademy requested changes
make refactoring of your tests

2024-07-18 11:25 UTC, MentorMateAcademy commented on src/main/java/com/example/demo/controller/CategoryController.java
> +
Why do you need this line?

2024-07-18 11:25 UTC, MentorMateAcademy commented on src/main/java/com/example/demo/service/book/impl/BookServiceImpl.java
> +                             .toList();
fix your tabulation

2024-07-18 11:25 UTC, MentorMateAcademy commented on src/test/java/com/example/demo/controller/BookControllerTest.java
> +
tabulation

2024-07-18 11:25 UTC, MentorMateAcademy commented on src/test/java/com/example/demo/controller/BookControllerTest.java
> +                                        .setCategories(new HashSet<>());
if you use same books lets create method that build this entity and properties better save to constants and reuse it

2024-07-18 11:25 UTC, MentorMateAcademy commented on src/test/java/com/example/demo/service/category/impl/CategoryServiceImplTest.java
> +    private CategoryServiceImpl categoryService;
Place it after mocks

2024-07-19 18:05 UTC, okuzan approved these changes

2024-07-22 12:47 UTC, merged