added Roles
163onmyneck/online-shop-spring pull request #8
Opened 2024-04-12 14:01 UTC by 163onmyneck

2024-04-12 15:41 UTC, kerrrusha requested changes

2024-04-12 15:41 UTC, kerrrusha commented on src/main/java/com/example/demo/service/user/impl/UserServiceImpl.java
> +            user.setRoles(Set.of(roleRepository.findById(USER_ID).get()));
find by RoleName instead

2024-04-12 15:41 UTC, kerrrusha commented on src/main/java/com/example/demo/service/user/impl/UserServiceImpl.java
> +    private static final long USER_ID = 1;
```suggestion
```

2024-04-12 15:41 UTC, kerrrusha commented on src/main/java/com/example/demo/config/SecurityConfig.java
> +                    .requestMatchers("/auth/**","/swagger-ui/**")
```suggestion
                    .requestMatchers("/auth/**", "/swagger-ui/**")
```

2024-04-13 10:33 UTC, MentorMA approved these changes

2024-04-14 07:28 UTC, merged